---
http_interactions:
- request:
    method: get
    uri: http://127.0.0.1:8087/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Content-Type:
      - application/json
      Date:
      - Thu, 29 Jun 2017 21:35:42 GMT
      Accept-Ranges:
      - bytes
      Server:
      - Restlet-Framework/2.2.2
      Www-Authenticate:
      - Digest realm="Wowza", domain="/", nonce="MTQ5ODc3MjE0MjMxNjoyMWNiMDhmYmY1NmZiMmJiZTAxYTJmOTg2ZDZlMmZkYg==",
        algorithm=MD5, qop="auth"
      Access-Control-Expose-Headers:
      - Date,Server,Content-Type,Content-Length,WWW-Authenticate
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - OPTIONS,GET,PUT,DELETE,POST
      Access-Control-Allow-Headers:
      - Content-Type,User-Agent,If-Modified-Since,Cache-Control,Range,Authorization
      Connection:
      - keep-alive
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"message":"The request requires user authentication","wowzaServer":"4.7.0","success":false,"code":"401"}'
    http_version: 
  recorded_at: Thu, 29 Jun 2017 21:35:42 GMT
- request:
    method: get
    uri: http://127.0.0.1:8087/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - Digest username="hazemt"
      - algorithm="MD5"
      - cnonce="983372af3fe303dac42cb530a976cd05"
      - nc=00000001
      - nonce="MTQ5ODc3MjE0MjMxNjoyMWNiMDhmYmY1NmZiMmJiZTAxYTJmOTg2ZDZlMmZkYg=="
      - qop="auth"
      - realm="Wowza"
      - response="d6ecd2b191873c44b9ff93b725e397da"
      - uri="/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications"
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json
      Date:
      - Thu, 29 Jun 2017 21:35:42 GMT
      Accept-Ranges:
      - bytes
      Server:
      - Restlet-Framework/2.2.2
      Access-Control-Expose-Headers:
      - Date,Server,Content-Type,Content-Length,WWW-Authenticate
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - OPTIONS,GET,PUT,DELETE,POST
      Access-Control-Allow-Headers:
      - Content-Type,User-Agent,If-Modified-Since,Cache-Control,Range,Authorization
      Connection:
      - keep-alive
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"serverName":"_defaultServer_","applications":[]}'
    http_version: 
  recorded_at: Thu, 29 Jun 2017 21:35:42 GMT
recorded_with: VCR 3.0.3
