---
http_interactions:
- request:
    method: get
    uri: http://127.0.0.1:8087/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Content-Type:
      - application/json
      Date:
      - Sat, 01 Jul 2017 10:21:01 GMT
      Accept-Ranges:
      - bytes
      Server:
      - Restlet-Framework/2.2.2
      Www-Authenticate:
      - Digest realm="Wowza", domain="/", nonce="MTQ5ODkwNDQ2MTE2Nzo5ZjA3ZWYyYTQ1MWRkZDJhYWQ0MzYxMmQ2ZjU0YjM4ZA==",
        algorithm=MD5, qop="auth"
      Access-Control-Expose-Headers:
      - Date,Server,Content-Type,Content-Length,WWW-Authenticate
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - OPTIONS,GET,PUT,DELETE,POST
      Access-Control-Allow-Headers:
      - Content-Type,User-Agent,If-Modified-Since,Cache-Control,Range,Authorization
      Connection:
      - keep-alive
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"message":"The request requires user authentication","success":false,"wowzaServer":"4.7.0","code":"401"}'
    http_version: 
  recorded_at: Sat, 01 Jul 2017 10:21:01 GMT
- request:
    method: get
    uri: http://127.0.0.1:8087/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - Digest username="username"
      - algorithm="MD5"
      - cnonce="8edf84fba05cf6a5e8faf68eebd293c8"
      - nc=00000001
      - nonce="MTQ5ODkwNDQ2MTE2Nzo5ZjA3ZWYyYTQ1MWRkZDJhYWQ0MzYxMmQ2ZjU0YjM4ZA=="
      - qop="auth"
      - realm="Wowza"
      - response="c1d35716a11bb5d822eb0a669b0d891a"
      - uri="/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications"
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Content-Type:
      - application/json
      Date:
      - Sat, 01 Jul 2017 10:21:01 GMT
      Accept-Ranges:
      - bytes
      Server:
      - Restlet-Framework/2.2.2
      Www-Authenticate:
      - Digest realm="Wowza", domain="/", nonce="MTQ5ODkwNDQ2MTE3Mjo3ZDJmMThmMTQ4MTI2OTVhYjdlYTE4OWNiNGYzMTdmYg==",
        algorithm=MD5, qop="auth"
      Access-Control-Expose-Headers:
      - Date,Server,Content-Type,Content-Length,WWW-Authenticate
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - OPTIONS,GET,PUT,DELETE,POST
      Access-Control-Allow-Headers:
      - Content-Type,User-Agent,If-Modified-Since,Cache-Control,Range,Authorization
      Connection:
      - keep-alive
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"message":"The request requires user authentication","success":false,"wowzaServer":"4.7.0","code":"401"}'
    http_version: 
  recorded_at: Sat, 01 Jul 2017 10:21:01 GMT
recorded_with: VCR 3.0.3
