---
http_interactions:
- request:
    method: post
    uri: http://127.0.0.1:8087/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications
    body:
      encoding: UTF-8
      string: '{"appType":"apptype","name":"app_name"}'
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: Created
    headers:
      Content-Type:
      - application/json
      Date:
      - Sat, 01 Jul 2017 16:25:54 GMT
      Accept-Ranges:
      - bytes
      Server:
      - Restlet-Framework/2.2.2
      Access-Control-Expose-Headers:
      - Date,Server,Content-Type,Content-Length,WWW-Authenticate
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - OPTIONS,GET,PUT,DELETE,POST
      Access-Control-Allow-Headers:
      - Content-Type,User-Agent,If-Modified-Since,Cache-Control,Range,Authorization
      Connection:
      - keep-alive
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"success":true,"message":"Application (app_name) created successfully.","data":null}'
    http_version: 
  recorded_at: Sat, 01 Jul 2017 16:25:54 GMT
recorded_with: VCR 3.0.3
