---
http_interactions:
- request:
    method: get
    uri: http://127.0.0.1:8087/v2/servers/_defaultServer_/vhosts/_defaultVHost_/applications/not_existed_app/instances/_definst_
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 04 Jul 2017 15:07:29 GMT
      Accept-Ranges:
      - bytes
      Server:
      - Restlet-Framework/2.2.2
      Access-Control-Expose-Headers:
      - Date,Server,Content-Type,Content-Length,WWW-Authenticate
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Methods:
      - OPTIONS,GET,PUT,DELETE,POST
      Access-Control-Allow-Headers:
      - Content-Type,User-Agent,If-Modified-Since,Cache-Control,Range,Authorization
      Connection:
      - keep-alive
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"message":"The server has not found anything matching the request
        URI","success":false,"wowzaServer":"4.7.0","code":"404"}'
    http_version: 
  recorded_at: Tue, 04 Jul 2017 15:07:29 GMT
recorded_with: VCR 3.0.3
